### ISSUE TITLE
Windows install fails

### ISSUE THREAD

**Issue by maphew** [developmentseed/rio-viz#47]
Hi. A naive install of rio-viz on Win10 fails. It looks like because it's looking for a compiler or it's environment that doesn't exist in this platform. Sometimes this can be worked around by installing whatever library or tool wants to be compiled in another way, sometimes not. I created this issue to give heads up to anyone else wondering about using rio-viz in Windows. And, perhaps, after some experimentation I'll find a solution to post here too. ;-)

Recipe to date:
```
conda create -n rio-viz
conda activate rio-viz
conda install -c channel-forge -y rasterio
pip install rio-viz
```
...snip...
```
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: starlette-cramjam, titiler.core, cramjam, morecantile, geojson-pydantic, rio-color
  Building wheel for starlette-cramjam (setup.py) ... done
  Created wheel for starlette-cramjam: filename=starlette_cramjam-0.1.0-py3-none-any.whl size=5796 sha256=7b5f9d277d12b66050092e4eb1bec035c6f13a7888cd8411c9c6d3303e8bcd14
  Stored in directory: c:\users\mhwilkie\appdata\local\pip\cache\wheels\8c\82\de\827981655061787cbbaadaf309611ac5a9e0d1b868331fe41a
  Building wheel for titiler.core (setup.py) ... done
  Created wheel for titiler.core: filename=titiler.core-0.5.1-py3-none-any.whl size=23929 sha256=e1295277835806e9c0188b48ab168dc6a6515ac2bf1a0984f1fe9ff40768618e
  Stored in directory: c:\users\mhwilkie\appdata\local\pip\cache\wheels\fd\ff\e3\c745f024c74494ed3138aad612dc97ebe41689070574aa4f70
  Building wheel for cramjam (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cramjam (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [263 lines of output]
      Running `maturin pep517 build-wheel -i C:\apps\conda\envs\rio-viz\python.exe`
```
...snip...
```
      error: could not compile `zstd-safe`

      To learn more, run the command again with --verbose.
      warning: build failed, waiting for other jobs to finish...
      error: build failed
      ðŸ’¥ maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib --`
      ðŸ”— Found pyo3 bindings
      ðŸ\x90\x8d Found CPython 3.10 at C:\apps\conda\envs\rio-viz\python.exe
      error: linking with `link.exe` failed: exit code: 1
```
...snip...

```
      note: `link.exe` returned an unexpected error


      note: you may need to install Visual Studio build tools with the "C++ build tools" workload


      error: aborting due to previous error


      Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\apps\\conda\\envs\\rio-viz\\python.exe'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cramjam
```
...snip...

```
Failed to build cramjam rio-color
ERROR: Could not build wheels for cramjam, rio-color, which is required to install pyproject.toml-based projects
```

**Comment by vincentsarago** [comment]
thanks for opening the issue @maphew. I have not idea what's going on and can't really test under window 😭. I feel moving to `pyproject.toml` https://flit.pypa.io/ should have made installation easier 😭

**Comment by maphew** [comment]
I keep reading about flit (and poetry) but have never tried them. Packaging systems are hard for my tiny brain. ;-)

`conda install cramjam` worked, but pip still tries to compile it anyway when processing `rio-color`. I then worked through the dependencies in pyproject.toml, trying combinations of `conda install X` and `pip install X --no-deps`. (My rule of thumb when working through something like this is to use conda when the package might need compiling and pip when I expect the package to be pure python.) This seemed to work to but `rio viz` is still issues traceback. I'll return later and try some other things.

```
(rio-viz) C:\Users\mhwilkie
$ pip install titiler --no-deps
Collecting titiler
  Using cached titiler-0.5.1-py3-none-any.whl
Installing collected packages: titiler
Successfully installed titiler-0.5.1

(rio-viz) C:\Users\mhwilkie
$ rio viz

Warning: entry point could not be loaded. Contact its author for help.

Traceback (most recent call last):
  File "C:\apps\conda\envs\rio-viz\lib\site-packages\click_plugins\core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "C:\apps\conda\envs\rio-viz\lib\site-packages\pkg_resources\__init__.py", line 2470, in load
    self.require(*args, **kwargs)
  File "C:\apps\conda\envs\rio-viz\lib\site-packages\pkg_resources\__init__.py", line 2493, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\apps\conda\envs\rio-viz\lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'titiler.core<0.6,>=0.5' distribution was not found and is required by the application
```

```
$ pip list
Package           Version
----------------- ---------
affine            2.3.1
asgiref           3.5.0
attrs             21.4.0
certifi           2021.10.8
click             8.1.2
click-plugins     1.1.1
cligj             0.7.2
colorama          0.4.4
cramjam           2.5.0
h11               0.13.0
numpy             1.22.3
pip               22.0.4
pyparsing         3.0.8
rasterio          1.2.10
rio-viz           0.9.3
setuptools        62.1.0
snuggs            1.4.7
starlette-cramjam 0.1.0
titiler           0.5.1
typing_extensions 4.1.1
uvicorn           0.17.6
wheel             0.37.1
```
```
$ conda list
# packages in environment at C:\apps\conda\envs\rio-viz:
#
# Name                    Version                   Build  Channel
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
asgiref                   3.5.0              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
boost-cpp                 1.74.0               h9f4b32c_8    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cairo                     1.16.0            h15b3021_1010    conda-forge
certifi                   2021.10.8       py310h5588dad_2    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
click                     8.1.2           py310h5588dad_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cramjam                   2.5.0           py310he2c049f_0    conda-forge
curl                      7.82.0               h789b8ee_0    conda-forge
expat                     2.4.8                h39d44d4_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
geos                      3.10.2               h39d44d4_0    conda-forge
geotiff                   1.7.1                h38b14a8_1    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
h11                       0.13.0             pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h57737ce_104    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_0    conda-forge
kealib                    1.4.14               h8995ca9_3    conda-forge
krb5                      1.19.3               hc8ab02b_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              14_win64_mkl    conda-forge
libcblas                  3.9.0              14_win64_mkl    conda-forge
libcurl                   7.82.0               h789b8ee_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.4.2                hc2921ad_4    conda-forge
libglib                   2.70.2               h3be07f2_4    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              14_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     14.2                 h1ea2d34_0    conda-forge
librttopo                 1.1.0                hb1df466_9    conda-forge
libspatialite             5.0.1               h36c16d9_15    conda-forge
libssh2                   1.10.0               h9a1e1f7_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxml2                   2.9.13               hf5bbc77_0    conda-forge
libzip                    1.8.0                h519de47_1    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.22.3          py310hcae7c84_2    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   3.0.2                h8ffe710_1    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   22.01.0              h24fffdf_2    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 he353ca9_0    conda-forge
proj                      9.0.0                h1cfcee9_1    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
python                    3.10.4          hcf16a7b_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
rasterio                  1.2.10          py310h41cc0dd_5    conda-forge
rio-viz                   0.9.3                    pypi_0    pypi
setuptools                62.1.0          py310h5588dad_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.38.2               h8ffe710_0    conda-forge
starlette-cramjam         0.1.0                    pypi_0    pypi
tbb                       2021.5.0             h2d74725_1    conda-forge
tiledb                    2.7.2                h47404fa_0    conda-forge
titiler                   0.5.1                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
uvicorn                   0.17.6          py310h5588dad_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h0e60522_4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
```

**Comment by vincentsarago** [comment]
stale
